version: '3'

tasks:
  1:
    cmds:
      - task: createSprint
  2:
    cmds:
      - task: runTests

  createSprint:
    cmds:
      - ./TASKS/createNewSprint.zsh
    silent: true

  runTests:
    cmds:
      - ./TASKS/tests.zsh
    silent: true

  setup:
    cmds:
      - ./TASKS/setup.zsh
    silent: true
